### ISSUE TITLE
Indiana Jones and The Fate of Atlantis mac

### ISSUE THREAD

**Issue by somaen** [symm/LAAExtract#1]
Just thought I'd chip in with the following:

Indy4 on the mac, has Atlantis.000 starting at offset 260224.

Since the .app-format is a bit weird, the path to the binary is:
The Fate of Atlantis.app/Contents/MacOS/The Fate of Atlantis

Relative to the SteamApps/common-folder.

**Comment by symm** [comment]
Thanks for the offset and details, I've added MacOS support for the other games also :)
